---
- hosts: all
  become: True
  ignore_errors: true
  gather_facts: yes
  #become_user: root

  tasks:
      - name: Create a file
        file:
          path: /tmp/playbookfile
          mode: '0755'
          state: touch
        tags:
           - file
      - name: Check something
        command: hahsajgdjadjahd
        tags:
           - cmd
       
        
      - name: Create a directory
        file:
          path: /tmp/dir
          mode: '0700'
          state: directory
        tags: 
           - dir
      - name: Create group
        group:
          name: security
          state: present

      - name: Add user Serge
        user:
          comment: Serge Admin
          shell: /bin/bash
          group: security
          name: serge
        when: ansible_os_family == "Iphone" or ansible_processor_nproc > 2
      - name:
        command: uptime
      - name: check the date
        shell: date