---
- hosts: ws
  become: yes
  ignore_errors: yes
  gather_facts: yes
  vars_files:
    - vars.yml
  tasks:
      - name: Download package
        get_url:
           url: "{{ LINK_URL }}"
           dest: "{{ DESTINATION }}"

      - name: Deleting the main.zip in tmp
        file:
          path: "{{ DESTINATION }}"
          state: absent

      