---
- hosts: ws
  become: yes
  tasks:
      - name: Install required packages
        package:
           state: present
           name: "{{ item }}"
        loop:
          - unzip
          - wget
          - httpd
      - name: Download artifact
        get_url:
           url: https://github.com/kserge2001/web-consulting/archive/refs/heads/dev.zip
           dest: /tmp/dev.zip
      - name: Unarchive zip file
        unarchive:
           src: /tmp/dev.zip
           remote_src: yes
           dest: /tmp
      - name: Copy artifact to html folder
        copy: 
          remote_src: yes
          src: /tmp/web-consulting-dev/
          dest: /var/www/html/
          owner: apache
          group: apache
          mode: '0755'
        # become: yes

      - name: Start Daemon
        systemd: 
          name: httpd
          state: started
          enabled: yes
        # become: yes
